using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanningApp
{
    // Base class User, containing common fields
    public class User
    {
        [Key] // Primary key UserId, a unique ID automatically generated by the database, incremented in sequence
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        // User account, unique identifier used by the user to log in, required, length must be 4-50 characters
        [Required] 
        [StringLength(50, MinimumLength = 4)] 
        public string UserAccount { get; set; }  

        [Required]
        [StringLength(50, MinimumLength = 6)]
        public string Password { get; set; }

        [Required]
        [Phone]
        public string PhoneNumber { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [StringLength(50)]
        public string Nickname { get; set; }

    }

    public class Customer : User
    {
        // Collection function, store a comma-separated list of attraction IDs
        public string Favorites { get; set; }
    }
    public class Staff : User
    {
        // If you have additional fields, you can add them here
    }
}








